//
//  RealHTTPSRedirectIntegrationTests.swift
//  ConsumerIntegrationTests
//
//  Opt-in, real-network redirect evidence for the public Producer facade.
//  Start Producer/scripts/test-support/local-https-redirect-server.py with a
//  CA generated by make-test-ca.sh, install that CA into the dedicated
//  simulator, and export the variables documented below before running.
//
//  The server keeps evidence in memory and exposes it only through the source
//  HTTPS endpoint's fixed /__evidence response. JSONL files are host-side
//  diagnostics only and are never read by this XCTest target.
//

import Foundation
import XCTest
import VolcengineTLSProducer

/// Required process environment:
///   TLS_RUN_REAL_REDIRECT=1
///   TLS_REDIRECT_ENDPOINT (or TLS_REDIRECT_SOURCE_ENDPOINT)
///
/// Optional:
///   TLS_REDIRECT_EVIDENCE_URL (defaults to endpoint + /__evidence)
///   TLS_REDIRECT_SAME_ORIGIN_TOPIC=same-origin
///   TLS_REDIRECT_CROSS_HOST_TOPIC=cross-host
///   TLS_REDIRECT_CROSS_SCHEME_TOPIC=cross-scheme
///   TLS_REDIRECT_CROSS_PORT_TOPIC=cross-port
///   TLS_REDIRECT_REGION=cn-beijing
///   TLS_REDIRECT_PROJECT_ID=redirect-test-project
final class RealHTTPSRedirectIntegrationTests: XCTestCase {

    private enum RedirectCase: CaseIterable, Hashable {
        case sameOrigin
        case crossHost
        case crossScheme
        case crossPort

        var topicEnvironmentName: String {
            switch self {
            case .sameOrigin: return "TLS_REDIRECT_SAME_ORIGIN_TOPIC"
            case .crossHost: return "TLS_REDIRECT_CROSS_HOST_TOPIC"
            case .crossScheme: return "TLS_REDIRECT_CROSS_SCHEME_TOPIC"
            case .crossPort: return "TLS_REDIRECT_CROSS_PORT_TOPIC"
            }
        }

        var defaultTopic: String {
            switch self {
            case .sameOrigin: return "same-origin"
            case .crossHost: return "cross-host"
            case .crossScheme: return "cross-scheme"
            case .crossPort: return "cross-port"
            }
        }

        var targetRole: String? {
            switch self {
            case .sameOrigin: return nil
            case .crossHost: return "cross-host"
            case .crossScheme: return "cross-scheme"
            case .crossPort: return "cross-port"
            }
        }
    }

    private struct Fixture {
        let endpoint: String
        let evidenceURL: URL
        let region: String
        let projectID: String
        let topics: [RedirectCase: String]

        static func loadOrSkip() throws -> Fixture {
            let environment = ProcessInfo.processInfo.environment
            guard environment["TLS_RUN_REAL_REDIRECT"] == "1" else {
                throw XCTSkip(
                    "real HTTPS redirect tests are opt-in; set TLS_RUN_REAL_REDIRECT=1")
            }

            let endpoint = value(
                in: environment,
                names: ["TLS_REDIRECT_ENDPOINT", "TLS_REDIRECT_SOURCE_ENDPOINT"])
            guard let endpoint else {
                throw XCTSkip(
                    "redirect fixture variables are incomplete: TLS_REDIRECT_ENDPOINT")
            }

            let evidenceURL: URL
            if let configuredEvidence = value(
                in: environment,
                names: ["TLS_REDIRECT_EVIDENCE_URL"]) {
                guard let parsed = URLComponents(string: configuredEvidence),
                      parsed.scheme?.lowercased() == "https",
                      parsed.host?.isEmpty == false,
                      parsed.user == nil,
                      parsed.password == nil,
                      parsed.path == "/__evidence",
                      parsed.query == nil,
                      parsed.fragment == nil,
                      let url = parsed.url else {
                    throw XCTSkip(
                        "TLS_REDIRECT_EVIDENCE_URL must be an HTTPS /__evidence URL")
                }
                evidenceURL = url
            } else {
                guard var components = URLComponents(string: endpoint),
                      components.scheme?.lowercased() == "https",
                      components.host?.isEmpty == false else {
                    throw XCTSkip(
                        "TLS_REDIRECT_ENDPOINT must be an HTTPS URL with a host")
                }
                components.path = "/__evidence"
                components.query = nil
                components.fragment = nil
                guard let url = components.url else {
                    throw XCTSkip("could not derive redirect evidence URL")
                }
                evidenceURL = url
            }

            let topics = Dictionary(uniqueKeysWithValues: RedirectCase.allCases.map { testCase in
                let topic = value(
                    in: environment,
                    names: [testCase.topicEnvironmentName]) ?? testCase.defaultTopic
                return (testCase, topic)
            })
            return Fixture(
                endpoint: endpoint,
                evidenceURL: evidenceURL,
                region: value(in: environment, names: ["TLS_REDIRECT_REGION"])
                    ?? "cn-beijing",
                projectID: value(in: environment, names: ["TLS_REDIRECT_PROJECT_ID"])
                    ?? "redirect-test-project",
                topics: topics)
        }

        func destination(for testCase: RedirectCase) -> Destination {
            Destination(
                endpoint: endpoint,
                region: region,
                projectID: projectID,
                topicID: topics[testCase]!)
        }

        private static func value(
            in environment: [String: String],
            names: [String]
        ) -> String? {
            for name in names {
                if let candidate = environment[name], !candidate.isEmpty {
                    return candidate
                }
            }
            return nil
        }
    }

    private struct EvidenceSnapshot: Decodable, Sendable {
        let source: [Bool]
        let cross_host: [Bool]
        let cross_scheme: [Bool]
        let cross_port: [Bool]

        func values(for role: String) -> [Bool] {
            switch role {
            case "source": return source
            case "cross-host": return cross_host
            case "cross-scheme": return cross_scheme
            case "cross-port": return cross_port
            default: return []
            }
        }
    }

    private enum EvidenceError: Error, CustomStringConvertible {
        case invalidResponse
        case invalidJSON
        case counterWentBack(String)

        var description: String {
            switch self {
            case .invalidResponse:
                return "redirect evidence endpoint returned an invalid response"
            case .invalidJSON:
                return "redirect evidence endpoint returned invalid JSON"
            case .counterWentBack(let role):
                return "redirect evidence counter went backwards for \(role)"
            }
        }
    }

    private struct Evidence {
        let results: [SendResult]
        let sourceAuthorization: [Bool]
        let targetAuthorization: [Bool]
    }

    private final class ResultCollector: @unchecked Sendable {
        private let lock = NSLock()
        private var values: [SendResult] = []

        func append(_ value: SendResult) {
            lock.lock()
            values.append(value)
            lock.unlock()
        }

        var snapshot: [SendResult] {
            lock.lock()
            defer { lock.unlock() }
            return values
        }
    }

    /// Fetches the fixed evidence response over HTTPS from inside the
    /// simulator. No host filesystem path or server-side JSONL is involved.
    private func fetchEvidence(from url: URL) async throws -> EvidenceSnapshot {
        var request = URLRequest(url: url)
        request.httpMethod = "GET"
        request.cachePolicy = .reloadIgnoringLocalCacheData
        request.timeoutInterval = 5
        let session = URLSession(configuration: .ephemeral)

        return try await withCheckedThrowingContinuation { continuation in
            let task = session.dataTask(with: request) { data, response, error in
                defer { session.finishTasksAndInvalidate() }
                if error != nil {
                    continuation.resume(throwing: error!)
                    return
                }
                guard let httpResponse = response as? HTTPURLResponse,
                      httpResponse.statusCode == 200,
                      let data else {
                    continuation.resume(throwing: EvidenceError.invalidResponse)
                    return
                }
                do {
                    let snapshot = try JSONDecoder().decode(
                        EvidenceSnapshot.self,
                        from: data)
                    continuation.resume(returning: snapshot)
                } catch {
                    continuation.resume(throwing: EvidenceError.invalidJSON)
                }
            }
            task.resume()
        }
    }

    private func waitForEvidence(
        from url: URL,
        sourceCountAtLeast count: Int,
        timeout: TimeInterval = 10
    ) async throws -> EvidenceSnapshot {
        let deadline = Date().addingTimeInterval(timeout)
        var latest = try await fetchEvidence(from: url)
        while latest.source.count < count && Date() < deadline {
            try await Task.sleep(nanoseconds: 50_000_000)
            latest = try await fetchEvidence(from: url)
        }
        return latest
    }

    private func delta(
        after: [Bool],
        before: [Bool],
        role: String
    ) throws -> [Bool] {
        guard after.count >= before.count else {
            throw EvidenceError.counterWentBack(role)
        }
        return Array(after.dropFirst(before.count))
    }

    private func run(
        _ testCase: RedirectCase,
        fixture: Fixture
    ) async throws -> Evidence {
        // Both snapshots are obtained through the HTTPS service endpoint.
        // GET /__evidence is intentionally excluded from POST accounting.
        let before = try await fetchEvidence(from: fixture.evidenceURL)
        let targetRole = testCase.targetRole
        let targetBefore = targetRole.map {
            before.values(for: $0)
        } ?? []

        let collector = ResultCollector()
        let callbackDelivered = expectation(description: "redirect terminal callback")
        callbackDelivered.assertForOverFulfill = false
        let configuration = try ProducerConfiguration(
            batch: BatchConfiguration(
                maxLogCount: 1,
                maxRawBytes: 1024 * 1024,
                linger: 0),
            connectTimeout: 3,
            requestTimeout: 5,
            automaticLifecycleHandling: false,
            destination: fixture.destination(for: testCase))
        let producer = try await Producer.open(
            configuration: configuration,
            credentials: Credentials(
                accessKeyID: "redirect-fixture-ak",
                accessKeySecret: "redirect-fixture-sk")) { result in
                    collector.append(result)
                    callbackDelivered.fulfill()
                }

        do {
            let event = LogEvent(contents: [
                "sdk_integration_test": .string("ios-simulator-https-redirect"),
                "nonce": .string(UUID().uuidString.lowercased()),
            ])
            try producer.add(event, mode: .immediate)
            await fulfillment(of: [callbackDelivered], timeout: 45)
            try await producer.close(timeout: 30)
        } catch {
            try? await producer.close(timeout: 30)
            throw error
        }

        let minimumSourceCount = before.source.count + 1
        let after = try await waitForEvidence(
            from: fixture.evidenceURL,
            sourceCountAtLeast: minimumSourceCount)
        let sourceDelta = try delta(
            after: after.source,
            before: before.source,
            role: "source")
        let targetDelta = try targetRole.map {
            try delta(
                after: after.values(for: $0),
                before: targetBefore,
                role: $0)
        } ?? []
        return Evidence(
            results: collector.snapshot,
            sourceAuthorization: sourceDelta,
            targetAuthorization: targetDelta)
    }

    func testRealHTTPSRedirectSameOriginPathChangeIsRejected() async throws {
        try await assertRejectedRedirect(.sameOrigin)
    }

    func testRealHTTPSRedirectCrossHostIsRejectedWithoutCredentialForwarding() async throws {
        try await assertRejectedRedirect(.crossHost)
    }

    func testRealHTTPSRedirectCrossSchemeIsRejectedWithoutCredentialForwarding() async throws {
        try await assertRejectedRedirect(.crossScheme)
    }

    func testRealHTTPSRedirectCrossPortIsRejectedWithoutCredentialForwarding() async throws {
        try await assertRejectedRedirect(.crossPort)
    }

    private func assertRejectedRedirect(_ testCase: RedirectCase) async throws {
        let fixture = try Fixture.loadOrSkip()
        let evidence = try await run(testCase, fixture: fixture)
        XCTAssertEqual(evidence.results.count, 1,
                       "one rejected batch must deliver exactly one terminal callback")
        let result = try XCTUnwrap(evidence.results.first)
        XCTAssertEqual(result.status, .failure,
                       "origin- or signature-changing redirect must be rejected")
        XCTAssertTrue(evidence.sourceAuthorization.allSatisfy { $0 },
                      "the source request may carry Authorization")
        XCTAssertEqual(evidence.sourceAuthorization.count, 1,
                       "a deterministic redirect rejection must not be retried")
        XCTAssertTrue(evidence.targetAuthorization.allSatisfy { !$0 },
                      "a rejected redirect target must never receive Authorization")
        XCTAssertEqual(evidence.targetAuthorization.count, 0,
                       "a rejected redirect must not issue a request to its target")
    }
}
